// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7tl0AeDHZQUmSnJJ0EjhIQ7vtvBeC5Hc',
    appId: '1:986227456229:web:d6aef48c8f932fc4f43c0c',
    messagingSenderId: '986227456229',
    projectId: 'fire-base-login-demo-ed04f',
    authDomain: 'fire-base-login-demo-ed04f.firebaseapp.com',
    storageBucket: 'fire-base-login-demo-ed04f.firebasestorage.app',
    measurementId: 'G-Z4H1RT976R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9uF_5XCap46S1TgSQwUEBEIpKePPX88',
    appId: '1:986227456229:android:12c21153e413db53f43c0c',
    messagingSenderId: '986227456229',
    projectId: 'fire-base-login-demo-ed04f',
    storageBucket: 'fire-base-login-demo-ed04f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5o4Isjxdw1QrcwwQSclojP6eT3Ar0Cck',
    appId: '1:986227456229:ios:cfbc9fda66ac7643f43c0c',
    messagingSenderId: '986227456229',
    projectId: 'fire-base-login-demo-ed04f',
    storageBucket: 'fire-base-login-demo-ed04f.firebasestorage.app',
    iosBundleId: 'com.example.firebaselogindemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5o4Isjxdw1QrcwwQSclojP6eT3Ar0Cck',
    appId: '1:986227456229:ios:cfbc9fda66ac7643f43c0c',
    messagingSenderId: '986227456229',
    projectId: 'fire-base-login-demo-ed04f',
    storageBucket: 'fire-base-login-demo-ed04f.firebasestorage.app',
    iosBundleId: 'com.example.firebaselogindemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7tl0AeDHZQUmSnJJ0EjhIQ7vtvBeC5Hc',
    appId: '1:986227456229:web:0bfa373910e0be85f43c0c',
    messagingSenderId: '986227456229',
    projectId: 'fire-base-login-demo-ed04f',
    authDomain: 'fire-base-login-demo-ed04f.firebaseapp.com',
    storageBucket: 'fire-base-login-demo-ed04f.firebasestorage.app',
    measurementId: 'G-5HBPP2VCTR',
  );
}
